In [6]:
import numpy
import os

In [2]:
def NN(m1, m2, w1, w2, b):
    z = m1 * w1 + m2 * w2 + b
    return sigmoid(z)

def sigmoid(x):
    return 1/(1 + numpy.exp(-x))

In [3]:
w1 = numpy.random.randn() #回傳具有常態分佈的數據
w2 = numpy.random.randn() #回傳具有常態分佈的數據
b = numpy.random.randn() #回傳具有常態分佈的數據

In [4]:
NN(3,1.5,w1,w2,b)

0.9906518535322886

In [8]:
phrases = ['看起來像', '我猜是', '我想是', '可能是', '看起來像是', '猜測....']
data = [[3,1.5,1],[2,1,0],[4,1.5,1],[3,1,0],[3.5,5,1],[2,0.5,0],[5.5,1,1],[1,1,0]]
rand_data = data[numpy.random.randint(len(data))] #隨機產生len(data)-1的index
m1 = rand_data[0]
m2 = rand_data[1]

prediction = NN(m1,m2,w1,w2,b)
prediction_text = ['藍色','紅色'][int(numpy.round(prediction))] #取四捨五入後的數值
phrase = numpy.random.choice(phrases) + "" + prediction_text #隨機取phrases
o =('這個' + phrase + "\n真的是"+ ['藍色','紅色'][rand_data[2]])
print(o)

NameError: name 'NN' is not defined

In [6]:
from gtts import gTTS
import os
tts = gTTS(o, lang='zh-tw')
tts.save("hello.mp3")

from pygame import mixer
mixer.init()
mixer.music.load('hello.mp3')
mixer.music.play()

In [46]:
## Advanced Neural network in numpy 可自行設定層數

import numpy as np

#Input array
X=np.array([[3,1.5],[2,1],[4,1.5],[3,1],[3.5,5],[2,0.5],[5.5,1],[1,1]])

#Output
y=np.array([[1],[1],[0],[0],[1],[0],[1],[0]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Sigmoid Function for backpropagation
def derivatives_sigmoid (x):
    return x * (1 - x)

#Variable initialization
epoch=50000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 20 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)#做內積
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

  #Backpropagation
  E = y-output #Loss差異
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T) #轉置後才能乘back_hidden_layer
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr #乘以學習率之後，再每次迴圈判斷Error
  bout += np.sum(d_output, axis=0,keepdims=True) *lr #乘以學習率之後，再每次迴圈判斷Error
  wh += X.T.dot(d_hiddenlayer) *lr 
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr #keepdims保持矩陣二維特性
    
  #numpy_E = np.array(E) 
  #Loss_E = np.sum((numpy_E)**2)/len(numpy_E)
  #print("E",Loss_E)
  
    
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]] 

predicted :
 [[0.99082698]
 [0.97970307]
 [0.01622142]
 [0.01618626]
 [0.99926164]
 [0.00816556]
 [0.98386654]
 [0.01271598]]


In [47]:
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[1]
 [1]
 [0]
 [0]
 [1]
 [0]
 [1]
 [0]] 

predicted :
 [[0.99082698]
 [0.97970307]
 [0.01622142]
 [0.01618626]
 [0.99926164]
 [0.00816556]
 [0.98386654]
 [0.01271598]]


In [41]:
#prediction = NN(m1,m2,w1,w2,b)
phrases = ['看起來像', '我猜是', '我想是', '可能是', '看起來像是', '猜測....']
prediction_text = ['藍色','紅色'][int(numpy.round(output[0]))] #取四捨五入後的數值
phrase = numpy.random.choice(phrases) + "" + prediction_text #隨機取phrases
o = '這個' + phrase + "\n真的是"+ ['藍色','紅色'][int(y[0])]
print(o)

這個我想是紅色
真的是紅色


1

In [52]:
## Advanced Neural network in numpy 可自行設定層數

import numpy as np

#Input array
X=np.array([[0,0,1],[0,1,0],[1,0,0],[0,0,1],[0,1,0],[1,0,0]])

#Output
y=np.array([[0],[1],[1],[0],[1],[1]])

#Sigmoid Function
def sigmoid (x):
    return 1/(1 + np.exp(-x))

#Sigmoid Function for backpropagation
def derivatives_sigmoid (x):
    return x * (1 - x)

#Variable initialization
epoch=50000 #Setting training iterations
lr=0.1 #Setting learning rate
inputlayer_neurons = X.shape[1] #number of features in data set
hiddenlayer_neurons = 20 #number of hidden layers neurons
output_neurons = 1 #number of neurons at output layer

#weight and bias initialization
wh=np.random.uniform(size=(inputlayer_neurons,hiddenlayer_neurons)) #均勻分布
bh=np.random.uniform(size=(1,hiddenlayer_neurons))
wout=np.random.uniform(size=(hiddenlayer_neurons,output_neurons))
bout=np.random.uniform(size=(1,output_neurons))

for i in range(epoch):
  #Forward Propogation
  hidden_layer_input1=np.dot(X,wh)#做內積
  hidden_layer_input=hidden_layer_input1 + bh
  hiddenlayer_activations = sigmoid(hidden_layer_input)
  output_layer_input1=np.dot(hiddenlayer_activations,wout)
  output_layer_input= output_layer_input1+ bout
  output = sigmoid(output_layer_input)

  #Backpropagation
  E = y-output #Loss差異
  back_output_layer = derivatives_sigmoid(output)
  back_hidden_layer = derivatives_sigmoid(hiddenlayer_activations)
  d_output = E * back_output_layer
  Error_at_hidden_layer = d_output.dot(wout.T) #轉置後才能乘back_hidden_layer
  d_hiddenlayer = Error_at_hidden_layer * back_hidden_layer
  wout += hiddenlayer_activations.T.dot(d_output) *lr #乘以學習率之後，再每次迴圈判斷Error
  bout += np.sum(d_output, axis=0,keepdims=True) *lr #乘以學習率之後，再每次迴圈判斷Error
  wh += X.T.dot(d_hiddenlayer) *lr 
  bh += np.sum(d_hiddenlayer, axis=0,keepdims=True) *lr #keepdims保持矩陣二維特性
    
  #numpy_E = np.array(E) 
  #Loss_E = np.sum((numpy_E)**2)/len(numpy_E)
  #print("E",Loss_E)
  
    
print('actual :\n', y, '\n')
print('predicted :\n', output)

actual :
 [[0]
 [1]
 [1]
 [0]
 [1]
 [1]] 

predicted :
 [[0.00518985]
 [0.99643878]
 [0.99646974]
 [0.00518985]
 [0.99643878]
 [0.99646974]]
